#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

ipath=".test.env.ts"
git diff --cached --name-only | if grep -qE "^$ipath$";then
    git reset HEAD -- "$ipath"
    echo "Warn: $ipath is removed from the index. It's not allowed to be committed."
fi
npx lint-staged
