name: Build

on:
  push:
    branches:
      - master

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16

      - name: Install Dependencies
      run: |
        npm install -g pnpm
        pnpm install
        pnpm config set strict-peer-dependencies false
        pnpm config set auto-install-peers true

      - name: Build Electron App for Windows
      if: matrix.os == 'windows-latest'
      run: pnpm run build:win
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Build Electron App for MacOS
        if: matrix.os == 'macos-latest'
        run: pnpm run build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dist/!(*.exe)"

      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          npx rimraf "dist/!(*.dmg)"

      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: dist

      - name: release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'dist/**'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
